services:
    php_test.product:
        class: PHPTestBundle\Service\ProductService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@fpn_tag.tag_manager'
        calls:
            - [setProductRepository, ['PHPTestBundle:Product'] ]
            - [setTagRepository, ['PHPTestBundle:Tag'] ]