<?php

namespace PHPTestBundle\Repository;

/**
 * Class ProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Custom findAllOrderedByInsertDate method.
     *
     * @param $sort
     *
     * @return array
     */
    public function findAllOrderedByInsertDate($sort = 'ASC')
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM '.$this->getEntityName().' p ORDER BY p.createdAt '.$sort
            )
            ->getResult();
    }

    /**
     * Find products by ids.
     *
     * @param $ids
     * @param $sort
     *
     * @return array
     */
    public function findByIds($ids, $sort = 'ASC')
    {
        return $this->findBy(
            array(
                'id' => $ids,
            )
        );
    }
}
