<?php

namespace PHPTestBundle\Repository;

/**
 * Class TagRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \DoctrineExtensions\Taggable\Entity\TagRepository
{
    /**
     * Find tags using LIKE.
     *
     * @param $query
     *
     * @return mixed
     */
    public function findTagsUsingLike($query)
    {
        return $this->getEntityManager()->getRepository($this->getEntityName())->createQueryBuilder('tag')
            ->select('tagging.resourceId')
            ->join('tag.tagging', 'tagging')
            ->where('tagging.resourceType = :resourceType')
            ->andwhere('tag.name LIKE :query')
            ->setParameter('query', '%'.$query.'%')
            ->setParameter('resourceType', 'tag')
            ->getQuery()
            ->execute()
        ;
    }
}
